[package]
name = "classicube-helpers"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
detour = "0.7.1"
futures = { version = "0.3.4", optional = true }
