[package]
name = "classicube-helpers"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
futures = { version = "0.3.5", optional = true }
log = "0.4.11"
paste = "1.0.0"

[features]
ci = []



# remove when 1.1.9 releases
[patch."https://github.com/SpiralP/rust-classicube-sys.git"]
classicube-sys = { git = "https://github.com/SpiralP//rust-classicube-sys", branch = "next" }
