var N = null;var sourcesIndex = {};
sourcesIndex["arrayvec"] = {"name":"","files":["array.rs","array_string.rs","char.rs","errors.rs","lib.rs","maybe_uninit.rs"]};
sourcesIndex["bitflags"] = {"name":"","files":["lib.rs"]};
sourcesIndex["cfg_if"] = {"name":"","files":["lib.rs"]};
sourcesIndex["classicube_helpers"] = {"name":"","dirs":[{"name":"entities","files":["entity.rs","mod.rs"]},{"name":"event_handler","files":["chat.rs","entity.rs","input.rs","mod.rs","net_events.rs","pointer.rs","tab_list.rs","tick.rs"]},{"name":"tab_list","files":["entry.rs","mod.rs"]}],"files":["callback_handler.rs","lib.rs","shared.rs"]};
sourcesIndex["classicube_sys"] = {"name":"","dirs":[{"name":"command","files":["mod.rs","owned_chat_command.rs"]},{"name":"vectors","files":["ivec3.rs","mod.rs","vec3.rs"]}],"files":["bindings.rs","chat.rs","event.rs","input.rs","lib.rs","packed_col.rs","string.rs","world.rs"]};
sourcesIndex["detour"] = {"name":"","dirs":[{"name":"alloc","files":["mod.rs","proximity.rs","search.rs"]},{"name":"arch","dirs":[{"name":"x86","dirs":[{"name":"thunk","files":["mod.rs","x64.rs","x86.rs"]},{"name":"trampoline","files":["disasm.rs","mod.rs"]}],"files":["meta.rs","mod.rs","patcher.rs"]}],"files":["detour.rs","memory.rs","mod.rs"]},{"name":"detours","files":["generic.rs","mod.rs","raw.rs","statik.rs"]},{"name":"pic","files":["emitter.rs","mod.rs","thunk.rs"]}],"files":["error.rs","lib.rs","macros.rs","traits.rs","util.rs"]};
sourcesIndex["generic_array"] = {"name":"","files":["arr.rs","functional.rs","hex.rs","impls.rs","iter.rs","lib.rs","sequence.rs"]};
sourcesIndex["kernel32"] = {"name":"","files":["lib.rs"]};
sourcesIndex["lazy_static"] = {"name":"","files":["inline_lazy.rs","lib.rs"]};
sourcesIndex["libc"] = {"name":"","dirs":[{"name":"windows","files":["mod.rs","msvc.rs"]}],"files":["fixed_width_ints.rs","lib.rs","macros.rs"]};
sourcesIndex["libudis86_sys"] = {"name":"","files":["api.rs","itab.rs","lib.rs","types.rs"]};
sourcesIndex["mmap_fixed"] = {"name":"","files":["lib.rs"]};
sourcesIndex["paste"] = {"name":"","files":["lib.rs"]};
sourcesIndex["paste_impl"] = {"name":"","files":["enum_hack.rs","lib.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["fallback.rs","lib.rs","strnom.rs","wrapper.rs"]};
sourcesIndex["proc_macro_hack"] = {"name":"","files":["error.rs","lib.rs","parse.rs","quote.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["region"] = {"name":"","dirs":[{"name":"os","files":["mod.rs","windows.rs"]}],"files":["error.rs","lib.rs","lock.rs","page.rs","protect.rs"]};
sourcesIndex["slice_pool"] = {"name":"","dirs":[{"name":"sync","files":["mod.rs","owned.rs"]},{"name":"unsync","files":["mod.rs","owned.rs"]}],"files":["lib.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["gen_helper.rs"]}],"files":["attr.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs"]};
sourcesIndex["typenum"] = {"name":"","files":["array.rs","bit.rs","int.rs","lib.rs","marker_traits.rs","operator_aliases.rs","private.rs","type_operators.rs","uint.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
sourcesIndex["winapi"] = {"name":"","dirs":[{"name":"km","files":["mod.rs"]},{"name":"shared","files":["basetsd.rs","cfg.rs","devpropdef.rs","guiddef.rs","ktmtypes.rs","minwindef.rs","mod.rs","ntdef.rs","ntstatus.rs","rpcndr.rs","windef.rs","winerror.rs","wtypesbase.rs"]},{"name":"um","dirs":[{"name":"gl","files":["mod.rs"]}],"files":["cfgmgr32.rs","consoleapi.rs","errhandlingapi.rs","fileapi.rs","libloaderapi.rs","memoryapi.rs","minwinbase.rs","mod.rs","processenv.rs","processthreadsapi.rs","sysinfoapi.rs","winbase.rs","wincon.rs","wincontypes.rs","wingdi.rs","winnt.rs","winreg.rs"]},{"name":"vc","files":["excpt.rs","mod.rs","vadefs.rs","vcruntime.rs"]},{"name":"winrt","files":["mod.rs"]}],"files":["lib.rs","macros.rs"]};
createSourceSidebar();
